; PlatformIO Project Configuration File — ESP32_PCB Traffic Light Controller
; https://docs.platformio.org/page/projectconf.html

; ── Network & MQTT ─────────────────────────────────────────────────────────────
[network]
wifi_ssid       = ChouHome
wifi_pass       = chou150197
mqtt_broker_ip  = 192.168.2.27
mqtt_broker_port= 1883
device_name     = pcb-tl-01

; ── Traffic Light GPIO ─────────────────────────────────────────────────────────
[traffic]
pin_red         = 21
pin_yellow      = 47
pin_green       = 14
pin_sdi         = 38
pin_scl         = 39
pin_kload       = 40
pin_btn_red     = 1
pin_btn_green   = 2
tl_red_ms       = 5000
tl_yellow_ms    = 2000
tl_green_ms     = 7000

[env:esp32-s3-devkitc-1]
platform = espressif32
board    = esp32-s3-devkitc-1
framework = arduino

; Chip N8R8
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0

build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    '-DWIFI_SSID="${network.wifi_ssid}"'
    '-DWIFI_PASS="${network.wifi_pass}"'
    '-DMQTT_BROKER_IP="${network.mqtt_broker_ip}"'
    -DMQTT_BROKER_PORT=${network.mqtt_broker_port}
    '-DDEVICE_NAME="${network.device_name}"'
    -DTL_PIN_RED=${traffic.pin_red}
    -DTL_PIN_YELLOW=${traffic.pin_yellow}
    -DTL_PIN_GREEN=${traffic.pin_green}
    -DTL_PIN_SDI=${traffic.pin_sdi}
    -DTL_PIN_SCL=${traffic.pin_scl}
    -DTL_PIN_KLOAD=${traffic.pin_kload}
    -DTL_PIN_BTN_RED=${traffic.pin_btn_red}
    -DTL_PIN_BTN_GREEN=${traffic.pin_btn_green}
    -DTL_RED_MS=${traffic.tl_red_ms}
    -DTL_YELLOW_MS=${traffic.tl_yellow_ms}
    -DTL_GREEN_MS=${traffic.tl_green_ms}

monitor_speed = 115200